### ISSUE TITLE
Feedback wanted

### ISSUE THREAD

**Issue by dteviot** [dteviot/DriveByEditor#1]
@belldandu, @typhoon71, @toshiya44, @dreamer2908
I've created a new Chrome extension that's intended to make it easier for people to send corrections to Light Novel translators.
The idea is, while viewing the web page in a browser (currently only Chrome) you can mark up any errors directly on the web page.
So, you can mark them as you see them.

Basic steps are:
1. Load the extension.  See https://github.com/dteviot/DriveByEditor for instructions.
2. Browse to a web page you want to read.
3. When you notice an error:  
   1. Select the text (Left click on the text and drag the mouse to highlight the text.)
   2. Right click mouse.  
   3. Select "Drive By Editor" in the menu.
   4. Now select option.  Add/Delete/Modify text.
   5. If Add or Modify is selected, type the new text into the edit box that appears, then click apply.
4. Continue reading page.
5. When finished reading page
   1. Right click anywhere on page.
   2. Select "Drive by Editor", then "Save to File"

This will save the entire page with marked up changes, so you could e-mail it to the translator.
Or, you can search the document for the text {(edit)} and copy just the changes if you want.

Anyway, I was hoping you could give this a test drive and give me your feedback before I release to Chrome store (and build a Firefox version.)
Questions.
1. Do you think this is useful?
2. Can you suggest any obvious improvements?
3. Suggestions on how I can make people aware of it?

Thanks.

**Comment by toshiya44** [comment]
I tried it on Chromium 60.0.3110.0. Works pretty smoothly.

The only suggestion I can think of is, instead of saving the entire page, give an option to export only the diff with 3-4 lines of context. 

This is indeed quite useful. We can advertise it in Baka-Tsuki forum as a starting point. 

Edit: Keyboard shortcut would be nice too.

**Comment by typhoon71** [comment]
I second the suggestion of exporting only the diff with 3-4 lines of context.

Also, for making ppl aware of it, I think wuxiaworld could be a fine place too.
They shouldn't be bothered by you making webtoepub, because most novels there are donationware.

The issue I'm thinking is that translators usually don't like ppl grabbing "their" work, both because "they did it" and for the ads money. So while the idea of DriveByEditor is really a good one, it may be affected by the other extension (webtoepub) in a bad way.

This mostly applies to "lone TLs", which sometime think they own stuff put on the web...

**Comment by dteviot** [comment]
@toshiya44 @typhoon71 
Thanks for the feedback

**Comment by dteviot** [comment]
@toshiya44 @typhoon71
I've updated the DriveByEditor.  
* Firefox (v 52 and above) supported
* Now copies the edits to the clipboard, rather than a file.  Should make easier to paste into an email (or a comments section on page)

What do you think?

**Comment by typhoon71** [comment]
Having the edits in the clipboard is good, but they aren't formatted so they are hard to read.
It would be nice if they were formatted (red/green) too.
Right now selecting the edited parts from the webpage, copying and pasting into the email is more readable.

**Comment by dteviot** [comment]
@typhoon71
Thanks for the feedback.
I've updated to write the edits to the clipboard as formatted HTML as well as text.
So if pasted into suitable target, the edit uses color (and other formatting.)
Please let me know what you think.

**Comment by typhoon71** [comment]
I think it looks fine. Clear and easy to understand. 
Now we only need to prepare for an invasion... by an army of editors! XD

**Comment by dteviot** [comment]
@typhoon71 
Excellent.  Have submitted to Mozilla for approval.
